GTCEuStartupEvents.registry('gtceu:material', event => {

    event.create('dirty_ancient_debris')
        .dust()
        .color(0x6E260E)
        .iconSet(GTMaterialIconSet.ROUGH)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('purified_ancient_debris')
        .dust()
        .color(0x6E260E)
        .iconSet(GTMaterialIconSet.ROUGH)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('ignisium_sulfide')
        .dust()
        .fluid()
        .color(0xE1C16E)
        .formula('IgS2')
        .iconSet(GTMaterialIconSet.ROUGH)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('ignisium')
        .dust()
        .fluid()
        .color(0xA52A2A)
        .formula('Ig')
        .iconSet(GTMaterialIconSet.ROUGH)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('stygian_slag')
        .dust()
        .color(0x5C4033)
        .formula('St')
        .iconSet(GTMaterialIconSet.ROUGH)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('stygian_solution')
        .fluid()
        .color(0x988558)
        .formula('St')
        .iconSet(GTMaterialIconSet.ROUGH)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('muddy_infernit')
        .dust()
        .color(0x800000)
        .formula('In')
        .iconSet(GTMaterialIconSet.ROUGH)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('infernit_slurry')
        .fluid()
        .color(0x800000)
        .formula('In')
        .iconSet(GTMaterialIconSet.ROUGH)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('infernit')
        .dust()
        .color(0x800000)
        .formula('In')
        .iconSet(GTMaterialIconSet.ROUGH)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

})