GTCEuStartupEvents.registry('gtceu:material', event => {

    event.create('delirium')
        .ore()
        .color(0x626361)
        .formula('Dm')
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES, GTMaterialFlags.NO_ORE_PROCESSING_TAB)

    event.create('delirium_slurry')
        .liquid()
        .color(0x626361)
        .formula('Dm+')
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('delirium_gem')
        .gem()
        .color(0x626361)
        .formula('Dm')
        .iconSet(GTMaterialIconSet.ROUGH)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('poly_atarax_acid')
        .liquid()
        .color(0x722ad5)
        .formula('AtH3 + Ψ')
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('atarax')
        .ore()
        .color(0x4836c9)
        .formula('At')
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES, GTMaterialFlags.NO_ORE_PROCESSING_TAB)

    event.create('psi_particles')
        .liquid()
        .color(0xeb5514)
        .formula('Ψ')
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES, GTMaterialFlags.NO_ORE_PROCESSING_TAB)

    event.create('poly_atarium_solution')
        .dust()
        .liquid()
        .color(0x8b609f)
        .formula('AtDmH3')
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('reinforced_delirium')
        .ingot()
        .color(0x4d525a)
        .blastTemp(3700)
        .formula('Dm2')
        .cableProperties(GTValues.VA[GTValues.MV], 64, 1, false)
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES, GTMaterialFlags.GENERATE_PLATE)

    event.create('reinforced_delirium_bad')
        .ingot()
        .color(0x5a6069)
        .blastTemp(3700)
        .formula('Dm2')
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

});