GTCEuStartupEvents.registry('gtceu:material', event => {

    event.create('grympl3')
        .ore()
        .color(0x72a857)
        .formula('Gr3')
        .iconSet(GTMaterialIconSet.DULL)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES, GTMaterialFlags.NO_ORE_PROCESSING_TAB)

    event.create('lambda_particles')
        .liquid()
        .color(0xffbd00)
        .formula('λ')
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('lambda_hydronyxium_solution')
        .liquid()
        .color(0xa2935d)
        .formula('λ - HNy2')
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('impuregrympl2')
        .gas()
        .color(0x9f607c)
        .formula('Gr2₋')
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('grympl2')
        .gas()
        .color(0x8e717a)
        .formula('Gr2')
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('stellarium_grympl2')
        .liquid()
        .color(0x619e99)
        .formula('SGr2')
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('sgrympl_slurry')
        .liquid()
        .color(0x2fb8d0)
        .formula('SGr2₋')
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('grympl1')
        .ingot()
        .liquid()
        .color(0x6d6e92)
        .formula('Gr1')
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('mirrored_grympl1')
        .ingot()
        .liquid()
        .color(0x94936b)
        .formula('1rG')
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES, GTMaterialFlags.GENERATE_PLATE)

    event.create('supergrympl')
        .ingot()
        .liquid()
        .color(0xe9df16)
        .formula('GRYMPL!')
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES, GTMaterialFlags.GENERATE_PLATE)

    event.create('grymploxideepoxilidas')
        .ingot()
        .liquid()
        .color(0x3d3d3d)
        .formula('3-Gr, 3,4-C19H23Cl2O3')
        .iconSet(GTMaterialIconSet.DULL)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_ROTOR)

});